EconomyAPI货币名称: 金币
Snowmn货币名称: 雪花
默认货币: EconomyAPI
自动更新: true
更新间隔: 86400
创建队伍价格: 50000
创建队伍币种: EconomyAPI
队伍初始人数上限: 8
队伍商城数量上限: 20
玩家初始声望: 10
队伍转交费用: 10000
一级称号价格: 1
二级称号价格: 100
三级称号价格: 5000
五级称号价格: 10000
六级称号价格: 10010
七级称号价格: 10086