EconomyAPI货币名称: 金币
Snowmn货币名称: 雪花
默认货币: EconomyAPI
自动更新: true
更新间隔: 86400
创建队伍价格: 50000
创建队伍币种: EconomyAPI
队伍初始人数上限: 8
队伍商城数量上限: 20
队伍消息上限: 100
队伍聊天内容限制长度: 0
玩家初始声望: 10
队伍转交费用: 10000
一级称号价格: 1
二级称号价格: 100
三级称号价格: 5000
五级称号价格: 10000
六级称号价格: 10010
七级称号价格: 10086
#插件的管理员
Admin: []
#显示是否只有插件管理员才可以更改插件属性
astrictAdmin: false
队长允许购买队伍称号: false
允许队长修改玩家声望: false
队伍签到声望: -1
底部显示: true
头部显示: true
#单位是ms
底部显示频率: 15
头部显示频率: 15
Tip: '§6时间： §a{Date} {Time}     §4{MoneyName}：§2{Money}  §d地图:§b{WorldName} {n}§8队伍: §9{TeamName}    §eVIP: §9{Vip}'
Top: §f{Player}     §4{TeamName}     §9{Sign}
底部顶部无解析对象: §4无
聊天功能: true
#聊天展现模式，当这个值为真时仅玩家可以看到消息
聊天限制模式: false
#当这个值小于等于零时不启用
聊天最大长度: -1
聊天文本: §b{WorldName}-{聊天队伍部分}{聊天VIP部分}{聊天称号部分}{Player}§f：§r{Msg}
聊天队伍部分: '[{TeamName}]'
聊天称号部分: '[{Sign}]'
聊天VIP部分: '[{Vip}]'
聊天填充: 无
#当这个值为真时将不再显示没有值的内容（如未加入队伍，不是VIP无称号等）
聊天缩放模式: true
#刷新VIP状态，单位是分钟
VIP刷新间隔: 10