name: Donthitme
main: cn.epicfx.winfxk.donthitme.Donthitme
api:
- 1.0.0
version: 1.0
website: http://Winfxk.EpicFX.cn
description: 一个不知道会不会有人用的聊天集合插件
author: Winfxk
loadbefore:
- EconomyAPI
- Snowmn
permissions:
   Donthitme.Command.main:
      description: Donthitme-Player
      default: true
   Donthitme.Command.Admin:
      description: Donthitme-Admin
      default: op